version: 2
jobs:
    build:
        docker:
            - image: 173481649355.dkr.ecr.ap-northeast-1.amazonaws.com/web:latest
              aws_auth:
                aws_access_key_id: AKIASQZCP4TFY6OXIRPX
                aws_secret_access_key: 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
        working_directory: /usr/local/bin
        environment:
            COMPOSER_URL: https://getcomposer.org/installer
            DOMPOSER_PATH: /usr/local/bin/composer
            DOCUMET_ROOT: /var/www/html
            PROJECT_PATH: /var/www/html/readingtohabit/readingtohabit
            UNITTEST_PATH: vendor/bin/phpunit
        
        steps:
            - run: curl -sS $COMPOSER_URL | php
            - run: mv composer.phar $COMPOSER_PATH
            - run: cd $DOCUMENT_ROOT
            - checkout
            - run: cd $PROJECT_PATH
            - run: composer install
            - run: php artisan config:cache
            - run: $UNITTEST_PATH
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
