version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-apache-node-browsers
      - image: circleci/mysql:5.7

    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - DB_CONNECTION: circle_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true
      - TZ: "Asia/Tokyo"

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo docker-php-ext-install pdo_mysql

      - run: |
          # TimezoneをAsia/Tokyoへ変更する
          sudo ln -fs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime &&
          sudo dpkg-reconfigure -f noninteractive tzdata
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./readingtohabit/composer.json" }}
            - v1-dependencies-

      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./readingtohabit
      
      - save_cache:
          paths:
            - ./readingtohabit/vendor
          key: v1-dependencies-{{ checksum "./readingtohabit/composer.json" }}
      
      - run:
          name: generate app_key
          command: cd ./readingtohabit; echo "APP_KEY=" > .env.testing; php artisan key:generate
      
      - run:
          name: Run PHPUnit
          command: cd ./readingtohabit; php artisan config:clear; vendor/bin/phpunit tests/Feature/AddArticleDoTest.php
