version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
    working_directory: ~/ci-demo
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./readingtohabit/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./readingtohabit
      - save_cache:
          paths:
            - ./readingtohabit/vendor
          key: v1-dependencies-{{ checksum "./readingtohabit/composer.json" }}
      - run:
          name: clear cache
          paths:
            - ./readingtohabit
          command: php artisan config:clear
      - run:
          name: Run PHPUnit
          command: ./readingtohabit/vendor/bin/phpunit ./readingtohabit/tests/Feature/RegisterUserCheckTest.php
